#!/bin/csh

foreach dir (E-MTAB-11174  E-MTAB-11697 D1_Nov2018_PB)
    cd $dir
    foreach p (*)
        echo "recompressing $dir/$p/outs"
        cd $p/outs
        rm all_contig_annotations.json
        cd ../..
    end
    cd ..
end
